#include "HandInput/Recognition/gesture_match_stabilizer.h"
#include <iostream>
#include <stdexcept>
namespace recognition=ryoiki::hand_input::recognition;
namespace { void require(bool value,const char* message){if(!value)throw std::runtime_error{message};}
recognition::GestureMatchCandidate match(std::uint32_t id,std::uint64_t now,std::uint64_t start,std::uint64_t end){return{id,.9F,now,start,end};}
void testConsecutiveAndNoMatch(){recognition::GestureMatchStabilizer value;auto a=match(7,2'000'000,500'000,1'900'000);require(value.process(&a).decision==recognition::GestureMatchDecision::WaitingForConsecutiveMatch,"First match was confirmed.");require(value.process(nullptr).decision==recognition::GestureMatchDecision::NoMatch,"No-match decision drifted.");require(value.process(&a).decision==recognition::GestureMatchDecision::WaitingForConsecutiveMatch,"No match did not reset consecutive count.");auto b=match(8,2'200'000,700'000,2'100'000);require(value.process(&b).decision==recognition::GestureMatchDecision::WaitingForConsecutiveMatch,"Gesture identity change did not restart count.");}
void testConfirmationDuplicateAndCooldownOrder(){recognition::GestureMatchStabilizer value;auto a=match(7,2'000'000,500'000,1'900'000);value.process(&a);require(value.process(&a).confirmed,"Second consecutive match was not confirmed.");auto overlap=match(7,2'200'000,600'000,2'100'000);value.process(&overlap);require(value.process(&overlap).decision==recognition::GestureMatchDecision::DuplicateSegmentSuppressed,"Duplicate must win over cooldown.");auto fresh=match(7,2'300'000,2'000'001,2'300'000);value.process(&fresh);require(value.process(&fresh).decision==recognition::GestureMatchDecision::Cooldown,"Non-overlap during cooldown was not suppressed.");auto ready=match(7,3'600'000,2'000'001,3'600'000);require(value.process(&ready).confirmed,"Post-cooldown match was not confirmed with preserved consecutive count.");}
void testResetSemantics(){recognition::GestureMatchStabilizer value;auto a=match(3,2'000'000,500'000,1'900'000);value.process(&a);value.process(&a);value.reset();auto overlap=match(3,4'000'000,600'000,1'800'000);value.process(&overlap);require(value.process(&overlap).decision==recognition::GestureMatchDecision::DuplicateSegmentSuppressed,"PR Reset incorrectly cleared duplicate history.");value.resetForRegistryChange();value.process(&overlap);require(value.process(&overlap).confirmed,"Registry reset retained stale suppression state.");}}
int main(){try{testConsecutiveAndNoMatch();testConfirmationDuplicateAndCooldownOrder();testResetSemantics();std::cout<<"Gesture match stabilizer tests passed.\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
