#include "HandInput/Recognition/gesture_template_serialization.h"
#include <bit>
#include <cstring>
#include <type_traits>
namespace ryoiki::hand_input::recognition { namespace {
struct Writer { std::vector<std::uint8_t> b; template<class T> void put(T v) { static_assert(std::is_arithmetic_v<T>); auto a=std::bit_cast<std::array<std::uint8_t,sizeof(T)>>(v); b.insert(b.end(),a.begin(),a.end()); } void text(const std::string&s){put(static_cast<std::uint32_t>(s.size()));b.insert(b.end(),s.begin(),s.end());} };
struct Reader { const std::uint8_t* p; std::size_t n,o{}; template<class T> bool get(T& v) { if(o+sizeof(T)>n)return false; std::array<std::uint8_t,sizeof(T)> a{}; std::memcpy(a.data(),p+o,sizeof(T)); o+=sizeof(T); v=std::bit_cast<T>(a); return true; } bool text(std::string&v){std::uint32_t size{};if(!get(size)||size>4096||o+size>n)return false;v.assign(reinterpret_cast<const char*>(p+o),size);o+=size;return true;} };
template<class S> void writeTopology(Writer&w,const S&s){w.put(s.firstFrameId);w.put(s.lastFrameId);w.put(s.durationUs);w.put(static_cast<std::uint64_t>(s.sampleCount));w.put(s.startFingerStateMask);w.put(s.endFingerStateMask);w.put(s.fingerStateTransitionCount);w.put(s.signedPalmAreaSignChanges);w.put(s.palmTravel);w.put(s.palmOrientationRangeRadians);w.put(s.handednessRange);w.put(s.handednessMean);w.put(s.fingerStraightnessRangeMax);w.put(s.signedPalmAreaRange);w.put(s.palmCompressionMin);w.put(s.palmCompressionMax);w.put(s.palmCompressionDrop);w.put(s.palmDepthRangeMax);w.put(s.palmTurnScore);w.put(s.handScaleRatioRange);w.put(s.handScaleRatioDelta);w.put(s.boundingBoxAreaRatioRange);w.put(s.boundingBoxAreaRatioDelta);w.put(s.translationDeltaX);w.put(s.translationDeltaY);w.put(s.translationDistance);w.put(s.topologyChangeScore);w.put(std::uint8_t{s.valid?1u:0u});}
bool readTopology(Reader&r,measurements::HandTopologySummary&s){std::uint64_t count{};std::uint8_t valid{}; return r.get(s.firstFrameId)&&r.get(s.lastFrameId)&&r.get(s.durationUs)&&r.get(count)&&(s.sampleCount=static_cast<std::size_t>(count),true)&&r.get(s.startFingerStateMask)&&r.get(s.endFingerStateMask)&&r.get(s.fingerStateTransitionCount)&&r.get(s.signedPalmAreaSignChanges)&&r.get(s.palmTravel)&&r.get(s.palmOrientationRangeRadians)&&r.get(s.handednessRange)&&r.get(s.handednessMean)&&r.get(s.fingerStraightnessRangeMax)&&r.get(s.signedPalmAreaRange)&&r.get(s.palmCompressionMin)&&r.get(s.palmCompressionMax)&&r.get(s.palmCompressionDrop)&&r.get(s.palmDepthRangeMax)&&r.get(s.palmTurnScore)&&r.get(s.handScaleRatioRange)&&r.get(s.handScaleRatioDelta)&&r.get(s.boundingBoxAreaRatioRange)&&r.get(s.boundingBoxAreaRatioDelta)&&r.get(s.translationDeltaX)&&r.get(s.translationDeltaY)&&r.get(s.translationDistance)&&r.get(s.topologyChangeScore)&&r.get(valid)&&(s.valid=valid!=0,true);}
}
std::vector<std::uint8_t> serializeGestureTemplate(const UnifiedSequenceTemplate&v){Writer w;w.put(kGestureTemplateFormatVersion);for(const auto&f:v.frames){w.put(f.timeOffsetMs);w.put(f.centerX);w.put(f.centerY);w.put(f.palmOrientationRadians);w.put(f.palmVelocity);for(float x:f.values)w.put(x);}writeTopology(w,v.topology);w.put(std::uint8_t{v.visualization.valid?1u:0u});for(const auto&f:v.visualization.frames){w.put(f.timeOffsetMs);w.put(f.centerX);w.put(f.centerY);for(const auto&p:f.skeleton){w.put(p.x);w.put(p.y);w.put(p.z);}}return std::move(w.b);}
bool deserializeGestureTemplate(const std::uint8_t*d,std::size_t n,UnifiedSequenceTemplate&v) noexcept {Reader r{d,n};std::uint32_t version{};if(!r.get(version)||version!=kGestureTemplateFormatVersion)return false;UnifiedSequenceTemplate out{};for(auto&f:out.frames){if(!r.get(f.timeOffsetMs)||!r.get(f.centerX)||!r.get(f.centerY)||!r.get(f.palmOrientationRadians)||!r.get(f.palmVelocity))return false;for(float&x:f.values)if(!r.get(x))return false;}if(!readTopology(r,out.topology))return false;std::uint8_t valid{};if(!r.get(valid))return false;out.visualization.valid=valid!=0;for(auto&f:out.visualization.frames){if(!r.get(f.timeOffsetMs)||!r.get(f.centerX)||!r.get(f.centerY))return false;for(auto&p:f.skeleton)if(!r.get(p.x)||!r.get(p.y)||!r.get(p.z))return false;}if(r.o!=n)return false;v=std::move(out);return true;}
std::vector<std::uint8_t> serializeTwoHandTemplate(const TwoHandTemplate&v){Writer w;w.put(kGestureTemplateFormatVersion);for(const auto&f:v.frames){w.put(f.timeOffsetMs);w.put(f.centerX);w.put(f.centerY);w.put(f.relativeAngleRadians);w.put(f.palmVelocity);for(float x:f.values)w.put(x);}const auto&s=v.summary;w.put(s.relativeTranslationDistance);w.put(s.relativeDistanceRange);w.put(s.relativeDistanceDelta);w.put(s.relativeAngleRangeRadians);w.put(s.lowHandednessMean);w.put(s.highHandednessMean);w.put(s.topologyChangeScore);w.put(s.meanRelativeDistance);w.put(static_cast<std::uint64_t>(v.sourceFrameCount));w.put(v.durationMs);w.put(std::uint8_t{v.valid?1u:0u});return std::move(w.b);}
bool deserializeTwoHandTemplate(const std::uint8_t*d,std::size_t n,TwoHandTemplate&v) noexcept {Reader r{d,n};std::uint32_t version{};if(!r.get(version)||version!=kGestureTemplateFormatVersion)return false;TwoHandTemplate out{};for(auto&f:out.frames){if(!r.get(f.timeOffsetMs)||!r.get(f.centerX)||!r.get(f.centerY)||!r.get(f.relativeAngleRadians)||!r.get(f.palmVelocity))return false;for(float&x:f.values)if(!r.get(x))return false;}auto&s=out.summary;std::uint64_t count{};std::uint8_t valid{};if(!r.get(s.relativeTranslationDistance)||!r.get(s.relativeDistanceRange)||!r.get(s.relativeDistanceDelta)||!r.get(s.relativeAngleRangeRadians)||!r.get(s.lowHandednessMean)||!r.get(s.highHandednessMean)||!r.get(s.topologyChangeScore)||!r.get(s.meanRelativeDistance)||!r.get(count)||!r.get(out.durationMs)||!r.get(valid)||r.o!=n)return false;out.sourceFrameCount=static_cast<std::size_t>(count);out.valid=valid!=0;v=std::move(out);return true;}
std::vector<std::uint8_t> serializeGestureRecording(const GestureRecordingProvenance&v){Writer w;w.put(kGestureTemplateFormatVersion);w.text(v.sourceId);w.put(v.takeIndex);w.put(v.capturedAtUs);w.put(v.durationMs);w.put(v.averageConfidence);const auto&q=v.quality;w.put(std::uint8_t{q.accepted?1u:0u});w.put(q.sourceFrameCount);w.put(q.validLandmarkFrameCount);w.put(q.highConfidenceFrameCount);w.put(q.effectiveFps);w.put(q.usableEffectiveFps);w.text(q.reason);w.put(static_cast<std::uint32_t>(v.frames.size()));for(const auto&f:v.frames){w.put(f.timeOffsetMs);w.put(f.handCount);for(float x:f.confidence)w.put(x);for(float x:f.handedness)w.put(x);for(const auto&hand:f.normalizedSkeletons)for(const auto&p:hand){w.put(p.x);w.put(p.y);w.put(p.z);}}return std::move(w.b);}
bool deserializeGestureRecording(const std::uint8_t*d,std::size_t n,GestureRecordingProvenance&v) noexcept{Reader r{d,n};std::uint32_t version{},count{};std::uint8_t accepted{};GestureRecordingProvenance out{};auto&q=out.quality;if(!r.get(version)||version!=kGestureTemplateFormatVersion||!r.text(out.sourceId)||!r.get(out.takeIndex)||!r.get(out.capturedAtUs)||!r.get(out.durationMs)||!r.get(out.averageConfidence)||!r.get(accepted)||!r.get(q.sourceFrameCount)||!r.get(q.validLandmarkFrameCount)||!r.get(q.highConfidenceFrameCount)||!r.get(q.effectiveFps)||!r.get(q.usableEffectiveFps)||!r.text(q.reason)||!r.get(count)||count>kMaxGestureRecordingFrames)return false;q.accepted=accepted!=0;out.frames.resize(count);for(auto&f:out.frames){if(!r.get(f.timeOffsetMs)||!r.get(f.handCount)||f.handCount>2)return false;for(float&x:f.confidence)if(!r.get(x))return false;for(float&x:f.handedness)if(!r.get(x))return false;for(auto&hand:f.normalizedSkeletons)for(auto&p:hand)if(!r.get(p.x)||!r.get(p.y)||!r.get(p.z))return false;}if(r.o!=n)return false;v=std::move(out);return true;}
}
